"""
Projects are a way to handle Python projects within Jedi. For simpler plugins
you might not want to deal with projects, but if you want to give the user more
flexibility to define sys paths and Python interpreters for a project,
:class:`.Project` is the perfect way to allow for that.

Projects can be saved to disk and loaded again, to allow project definitions to
be used across repositories.
"""
import json
from pathlib import Path
from itertools import chain
from jedi import debug
from jedi.api.environment import get_cached_default_environment, create_environment
from jedi.api.exceptions import WrongVersion
from jedi.api.completion import search_in_module
from jedi.api.helpers import split_search_string, get_module_names
from jedi.inference.imports import load_module_from_path, load_namespace_from_path, iter_module_names
from jedi.inference.sys_path import discover_buildout_paths
from jedi.inference.cache import inference_state_as_method_param_cache
from jedi.inference.references import recurse_find_python_folders_and_files, search_in_file_ios
from jedi.file_io import FolderIO
_CONFIG_FOLDER = '.jedi'
_CONTAINS_POTENTIAL_PROJECT = ('setup.py', '.git', '.hg', 'requirements.txt', 'MANIFEST.in', 'pyproject.toml')
_SERIALIZER_VERSION = 1

class Project:
    """
    Projects are a simple way to manage Python folders and define how Jedi does
    import resolution. It is mostly used as a parameter to :class:`.Script`.
    Additionally there are functions to search a whole project.
    """
    _environment = None

    @classmethod
    def load(cls, path):
        """
        Loads a project from a specific path. You should not provide the path
        to ``.jedi/project.json``, but rather the path to the project folder.

        :param path: The path of the directory you want to use as a project.
        """
        project_path = Path(path)
        config_path = project_path / _CONFIG_FOLDER / 'project.json'
        if config_path.exists():
            with open(config_path, 'r') as f:
                config = json.load(f)
            return cls(**config)
        return cls(path)

    def save(self):
        """
        Saves the project configuration in the project in ``.jedi/project.json``.
        """
        config = {
            'path': str(self._path),
            'environment_path': self._environment_path,
            'load_unsafe_extensions': self._load_unsafe_extensions,
            'sys_path': self._sys_path,
            'added_sys_path': self.added_sys_path,
            'smart_sys_path': self._smart_sys_path
        }
        config_path = self._path / _CONFIG_FOLDER
        config_path.mkdir(parents=True, exist_ok=True)
        with open(config_path / 'project.json', 'w') as f:
            json.dump(config, f, indent=4)

    def __init__(self, path, *, environment_path=None, load_unsafe_extensions=False, sys_path=None, added_sys_path=(), smart_sys_path=True) -> None:
        """
        :param path: The base path for this project.
        :param environment_path: The Python executable path, typically the path
            of a virtual environment.
        :param load_unsafe_extensions: Default False, Loads extensions that are not in the
            sys path and in the local directories. With this option enabled,
            this is potentially unsafe if you clone a git repository and
            analyze it's code, because those compiled extensions will be
            important and therefore have execution privileges.
        :param sys_path: list of str. You can override the sys path if you
            want. By default the ``sys.path.`` is generated by the
            environment (virtualenvs, etc).
        :param added_sys_path: list of str. Adds these paths at the end of the
            sys path.
        :param smart_sys_path: If this is enabled (default), adds paths from
            local directories. Otherwise you will have to rely on your packages
            being properly configured on the ``sys.path``.
        """
        if isinstance(path, str):
            path = Path(path).absolute()
        self._path = path
        self._environment_path = environment_path
        if sys_path is not None:
            sys_path = list(map(str, sys_path))
        self._sys_path = sys_path
        self._smart_sys_path = smart_sys_path
        self._load_unsafe_extensions = load_unsafe_extensions
        self._django = False
        self.added_sys_path = list(map(str, added_sys_path))
        'The sys path that is going to be added at the end of the '

    @property
    def path(self):
        """
        The base path for this project.
        """
        return self._path

    @property
    def sys_path(self):
        """
        The sys path provided to this project. This can be None and in that
        case will be auto generated.
        """
        return self._sys_path

    @property
    def smart_sys_path(self):
        """
        If the sys path is going to be calculated in a smart way, where
        additional paths are added.
        """
        return self._smart_sys_path

    @property
    def load_unsafe_extensions(self):
        """
        Whether the project loads unsafe extensions.
        """
        return self._load_unsafe_extensions

    @inference_state_as_method_param_cache()
    def _get_sys_path(self, inference_state, add_parent_paths=True, add_init_paths=False):
        """
        Keep this method private for all users of jedi. However internally this
        one is used like a public method.
        """
        if self._sys_path is not None:
            return self._sys_path

        sys_path = list(inference_state.get_sys_path())
        
        if self._smart_sys_path:
            check_sys_path_modifications = inference_state.project._get_sys_path_with_modifications
            sys_path = check_sys_path_modifications(inference_state, sys_path)

        if add_parent_paths:
            parent = self._path.parent
            while parent != self._path:
                sys_path.append(str(parent))
                parent = parent.parent

        sys_path.extend(self.added_sys_path)

        if add_init_paths:
            init_paths = []
            for p in sys_path:
                init_path = os.path.join(p, '__init__.py')
                if os.path.isfile(init_path):
                    init_paths.append(init_path)
            sys_path = init_paths + sys_path

        return sys_path

    def search(self, string, *, all_scopes=False):
        """
        Searches a name in the whole project. If the project is very big,
        at some point Jedi will stop searching. However it's also very much
        recommended to not exhaust the generator. Just display the first ten
        results to the user.

        There are currently three different search patterns:

        - ``foo`` to search for a definition foo in any file or a file called
          ``foo.py`` or ``foo.pyi``.
        - ``foo.bar`` to search for the ``foo`` and then an attribute ``bar``
          in it.
        - ``class foo.bar.Bar`` or ``def foo.bar.baz`` to search for a specific
          API type.

        :param bool all_scopes: Default False; searches not only for
            definitions on the top level of a module level, but also in
            functions and classes.
        :yields: :class:`.Name`
        """
        return self._search(string, all_scopes=all_scopes)

    def complete_search(self, string, **kwargs):
        """
        Like :meth:`.Script.search`, but completes that string. An empty string
        lists all definitions in a project, so be careful with that.

        :param bool all_scopes: Default False; searches not only for
            definitions on the top level of a module level, but also in
            functions and classes.
        :yields: :class:`.Completion`
        """
        return self._search(string, complete=True, **kwargs)

    def __repr__(self):
        return '<%s: %s>' % (self.__class__.__name__, self._path)

def _is_django_path(directory):
    """ Detects the path of the very well known Django library (if used) """
    return (os.path.basename(directory) == 'django'
            and os.path.isfile(os.path.join(directory, '__init__.py'))
            and os.path.isfile(os.path.join(directory, 'apps.py')))

def get_default_project(path=None):
    """
    If a project is not defined by the user, Jedi tries to define a project by
    itself as well as possible. Jedi traverses folders until it finds one of
    the following:

    1. A ``.jedi/config.json``
    2. One of the following files: ``setup.py``, ``.git``, ``.hg``,
       ``requirements.txt`` and ``MANIFEST.in``.
    """
    if path is None:
        path = os.getcwd()

    check_path = os.path.abspath(path)
    probable_path = None
    first_no_init_file = None
    for dir in traverse_parents(check_path):
        try:
            return Project.load(dir)
        except (FileNotFoundError, InvalidProjectError):
            pass

        if first_no_init_file is None:
            if os.path.exists(os.path.join(dir, '__init__.py')):
                probable_path = dir
            else:
                first_no_init_file = dir

        if any(os.path.exists(os.path.join(dir, p)) for p in _CONTAINS_POTENTIAL_PROJECT):
            return Project(dir)
    else:
        if probable_path is not None:
            return Project(probable_path)
        elif first_no_init_file is not None:
            return Project(first_no_init_file)

    curdir = path if os.path.isdir(path) else os.path.dirname(path)
    return Project(curdir)
